import turtle
screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('paleturquoise')
t=turtle.Turtle()
t.speed(0)

#grass
t.pencolor('forestgreen')
t.penup()
t.goto(-5000,-100)
t.pendown()
t.fillcolor('forestgreen')
t.begin_fill()
t.goto(5000,-100)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-100)
t.end_fill()

#sun
t.penup()
t.goto(300, 310)
t.pencolor("yellow")
t.fillcolor('yellow')
t.begin_fill()
t.circle(50)
t.end_fill()

# flower
t.pencolor('green')
t.penup()
t.goto(-100, -110)
t.pendown()
t.pensize(7)
t.goto(-100, -10)
t.penup()
t.goto(-110,28)
t.pendown()
t.pencolor('red')
t.fillcolor('red')
for i in range(6):
        t.begin_fill()
        t.circle(15)
        t.end_fill()
        t.penup()
        t.forward(20)
        t.right(60)
        t.pendown()
t.penup()
t.goto(-100,-10)
t.pendown()
t.pencolor('yellow')
t.fillcolor('yellow')
t.begin_fill()
t.circle(20)
t.end_fill()

#kite
t.pencolor('purple')
t.penup()
t.goto(0,150)
t.pendown()
t.fillcolor("purple")
t.begin_fill()
t.forward(50)
t.right(45)
t.forward(50)
t.right(135)
t.forward(50)
t.right(45)
t.forward(50)
t.right(135)
t.end_fill()

t.pensize(3)
t.penup()
t.goto(86,114)
t.pendown()
t.goto(170,80)


#cloud
t.penup()
t.goto(-250,300)
t.pendown()
t.pencolor('white')
t.fillcolor('white')
for i in range(10):
        t.begin_fill()
        t.circle(20)
        t.end_fill()
        t.penup()
        t.forward(18)
        t.right(70)
        t.pendown()
t.penup()
t.goto(-220,300)
t.pendown()
for i in range(10):
        t.begin_fill()
        t.circle(20)
        t.end_fill()
        t.penup()
        t.forward(18)
        t.right(70)
        t.pendown()
t.fillcolor('white')
t.begin_fill()
t.pencolor('white')
t.begin_fill()
t.penup()
t.goto(-225,290)
t.pendown()
t.circle(25)
t.end_fill()


t.fillcolor('white')
t.begin_fill()
t.pencolor('white')
t.begin_fill()
t.penup()
t.goto(-190,285)
t.pendown()
t.circle(25)
t.end_fill()

# tree
t.pencolor('brown')
t.penup()
t.goto(100, -140)
t.pendown()
t.pensize(15)
t.goto(100, -10)
t.penup()
t.goto(80,15)
t.pendown()
t.pencolor('green')
t.fillcolor('green')
for i in range(6):
        t.begin_fill()
        t.circle(15)
        t.end_fill()
        t.penup()
        t.forward(20)
        t.right(60)
        t.pendown()
t.penup()
t.goto(110,-10)
t.pendown()
t.pencolor('green')
t.fillcolor('green')
t.begin_fill()
t.circle(20)
t.end_fill()
t.penup()
t.goto(80,15)
t.pendown()
t.pencolor('green')
t.fillcolor('green')
for i in range(7):
        t.begin_fill()
        t.circle(25)
        t.end_fill()
        t.penup()
        t.forward(20)
        t.right(60)
        t.pendown()







# river
t.penup()
t.pencolor('blue')
t.fillcolor('blue')
t.begin_fill()
t.goto(-500,-300)
t.pendown()
t.goto(500,-300)
t.goto(500,-350)
t.goto(-500,-350)
t.goto(-500,-300)
t.end_fill()

t.penup()
t.pensize(1)
t.pencolor('dodgerblue')
t.goto(0,300)
t.write("  Spring 2025", align="center", font=("Arial", 40, "bold"))

t.penup()
t.goto(250, -100)
t.setheading(90)
t.pencolor("black")
t.pensize(3)
t.pendown()
t.forward(50)

t.pencolor("orange")
t.pensize(1)
t.goto(220, -50)
t.fillcolor("orange")
t.begin_fill()
t.goto(280, -50)
t.goto(250, 0)
t.goto(220, -50)
t.end_fill()






# baloon
t.pencolor('red')
t.fillcolor('red')
t.penup()
t.begin_fill()
t.goto(100,259)
t.pendown()
t.circle(30)
t.end_fill()
t.pencolor('black')
t.pensize(2)
t.goto(230,220)




turtle.done()